# Dataset Configuration
dataset:
  type: "cifar10"              # Dataset type ("mnist", "custom", "cifar10", ...)
  data_path: "./data"          # Data path
  image_size: 64                # Image size after resize
  channels: 3                  # Number of image channels(mnist: 1, cifar10: 3, ...)
  split_dataset: true          # Split dataset into train/val/test?
  split_ratio:                 # Train/validation/test split ratios
    train: 0.7
    validation: 0.2
    test: 0.1

# GAN Model Configuration
model:
  name: "dcgan"                # GAN model type ("dcgan", "wgan", "basic_gan")
  save_path: "./models"        # Path to save the model
  load_pretrained: False       # Load pretrained model?

# Training Configuration
training:
  device: "cuda"               # Device to use ("cuda" or "cpu")
  list_gpus: [0]               # List of GPU devices to use
  optimizer: "adam"           # Optimization algorithm (adam, rmsprop, sgd, adamw, nadam)
  batch_size: 32               # Batch size
  noise_dimension: 128         # Size of noise vector
  learning_rate: 0.00001        # Learning rate
  beta1: 0.5                   # Beta1 parameter for Adam optimizer
  num_epochs: 10               # Number of epochs
  save_interval: 100           # Save model every n iterations
  early_stop: False            # Enable early stopping?
  patience: 5                  # Patience for early stopping
  save_loss: True              # Save loss history?